networks:
  hackatoon-micro-services:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: hackatoon-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      hackatoon-micro-services:
        ipv4_address: 172.40.0.2

  grafana:
    image: grafana/grafana:latest
    container_name: hackatoon-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      hackatoon-micro-services:
        ipv4_address: 172.40.0.3

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hackatoon-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      hackatoon-micro-services:
        ipv4_address: 172.40.0.4

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hackatoon-sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@fiap2024"
      ACCEPT_EULA: "Y"
    networks:
      hackatoon-micro-services:
        ipv4_address: 172.40.0.5