apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-producer
  template:
    metadata:
      labels:
        app: product-producer
    spec:
      containers:
      - name: product-producer
        image: product-producer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: hackatoon-product-config
