apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackatoon-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackatoon-rabbitmq
  template:
    metadata:
      labels:
        app: hackatoon-rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - containerPort: 5672
          - containerPort: 15672
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_DEFAULT_USER
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_DEFAULT_PASS