apiVersion: v1
kind: ConfigMap
metadata:
  name: hackatoon-product-config
data:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "SQLConnection": "Server=hackatoon-sqlserver,1433;Database=HackatoonDb;User Id=sa;Password=@fiap2024;TrustServerCertificate=True;"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "RabbitMQ": {
        "HostName": "hackatoon-rabbitmq",
        "UserName": "guest",
        "Password": "guest",
        "VirtualHost": "/",
        "Port": 5672,
        "DefaultExchangeName": "topic_exchange",
        "DefaultExchangeType": "topic"
      }
    }